#values are defined via https://developer.webex-cx.com/my-apps and must be associated to a tenant
baseURL: https://webexapis.com/v1
client_id: C000000000c00aa0bd00000000fea000000ea000cb0000b000000d0b00ecd000a
client_secret: 00ec0b000f000000e00e000000d00d00df000ed0000a0000f0e0cc000b000c00
redirect_uri: http://localhost:8080
response_type: code
scope: cjp:config_read
state: test
grant_type: authorization_code

filesystem:
# this is the directory in-which database information will be persisted 
  dataDirectory: data
# fileSystemInterface: can be fileSystemLocalhost OR fileSystemAWSS3
  fileSystemInterface: fileSystemLocalhost

fileSystemAWSS3:
  accessKey: your_accessKey
  bucketName: your_bucketName
  secretKey: your_secretKey

logging:
  level:
    com:
      cisco: INFO
      mchange: INFO
    org:
      springframework: INFO

server:
  forward-headers-strategy: native
  port: 8080

spring:
  cache:
    type: NONE
